version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

jobs:
  job3:
    docker:
      - image: cimg/aws:2023.12
    environment:
      region: "ap-south-1"
    working_directory: ~/repo
    steps:
      - checkout

      - aws-cli/setup:
          aws-access-key-id: aws_access_key
          aws-secret-access-key: aws_secret_key
          region: region
      - run:
          name: Deleting README.md, .git and .circleci
          command: |
            ls -al
            rm -rf README.md .circleci .git check_state
            ls -al
      - aws-s3/sync:
          from: "./"
          to: "s3://circle-test-bucket-1/"
          # arguments: "--delete"
workflows:
  version: 2
  S3-sync-test:
    jobs:
      - job3
