version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  python: circleci/python@1.5.0
  

jobs:
  job1:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Step 1
          command: |
            apk update
            apk add jq
            ls
            
            ENV_1="$(cat env/environments.json | jq -r '.qa1.env')"
            echo "----------------"
            echo "$ENV_1"
            echo "----------------"
            echo "export fruit=apple" >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "$fruit"
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  job2:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
      - run: |
          # verify; this should print 'BAR'
          printenv fruit
      - run:
          name: Step 1
          command: |
            source "$BASH_ENV"
            echo "$fruit"
           
workflows:
  version: 2
  Infra-Setup-1:
    jobs:
      - job1
      - job2:
          requires:
            - job1
