version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  python: circleci/python@1.5.0


jobs:
  job1:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      # Uncomment and modify the following lines if needed
      # - aws-cli/setup:
      #     aws_access_key_id: aws_access_key
      #     aws_secret_access_key: aws_secret_key
      #     region: region

      # - aws-s3/sync:
      #     from: "Rapport_1.0/aws_data_pipelines/step_functions/src/RapportPipeline"
      #     to: "s3://prvs3-rp-config-${short_region}-${ENV}-01/step_functions/RapportPipeline/"

      - run:
          name: Step 1
          command: |
            echo "export fruit=apple" >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "$fruit"
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  job2:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      # Uncomment and modify the following lines if needed
      # - aws-cli/setup:
      #     aws_access_key_id: aws_access_key
      #     aws_secret_access_key: aws_secret_key
      #     region: region

      # - aws-s3/sync:
      #     from: "Rapport_1.0/aws_data_pipelines/step_functions/src/RapportPipeline"
      #     to: "s3://prvs3-rp-config-${short_region}-${ENV}-01/step_functions/RapportPipeline/"
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
      - run: |
          # verify; this should print 'BAR'
          printenv fruit
      - run:
          name: Step 1
          command: |
            source "$BASH_ENV"
            echo "$fruit"
           
workflows:
  version: 2
  Infra-Setup-1:
    jobs:
      - job1
      - job2:
          requires:
            - job1
